name: Terraform workflow

on:
  push:
    branches: ["main"]
    paths:
      - "env/non-prod/**"
      - "env/prod/**"

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to deploy (prod and non-prod)"
        options: 
          - non-prod
          - prod
        required: true
        default: "non-prod"


jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event_name == 'push' && 'non-prod' || github.event.inputs.environment }}
      
    permissions:
      contents: "read"
      id-token: "write"      

    defaults:
      run:
        working-directory: env/${{ github.event_name == 'push' && 'non-prod' || github.event.inputs.environment }}


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
          
      - name: Terraform Init
        run: terraform init -input=false -reconfigure

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan



  terraform-apply:
    name: Terraform apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event_name == 'push' && 'non-prod' || github.event.inputs.environment }}
      
    permissions:
      contents: "read"
      id-token: "write"      

    defaults:
      run:
        working-directory: env/${{ github.event_name == 'push' && 'non-prod' || github.event.inputs.environment }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"        
          
      - name: Terraform Init
        run: terraform init -input=false -reconfigure          

      - name: Terraform Apply 
        run: terraform apply -auto-approve 
      

